/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'iconic\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-spin-alt' : '&#xe06a;',
			'icon-spin' : '&#xe06b;',
			'icon-curved-arrow' : '&#xe06c;',
			'icon-undo' : '&#xe06d;',
			'icon-reload' : '&#xe06e;',
			'icon-reload-alt' : '&#xe06f;',
			'icon-loop' : '&#xe070;',
			'icon-loop-alt1' : '&#xe071;',
			'icon-loop-alt2' : '&#xe072;',
			'icon-loop-alt3' : '&#xe073;',
			'icon-loop-alt4' : '&#xe074;',
			'icon-transfer' : '&#xe075;',
			'icon-arrow-left' : '&#xe07c;',
			'icon-arrow-right' : '&#xe07f;',
			'icon-arrow-up' : '&#xe082;',
			'icon-arrow-down' : '&#xe085;',
			'icon-microphone' : '&#xe08a;',
			'icon-headphones' : '&#xe08b;',
			'icon-fullscreen-exit' : '&#xe095;',
			'icon-fullscreen-exit-alt' : '&#xe096;',
			'icon-fullscreen' : '&#xe097;',
			'icon-fullscreen-alt' : '&#xe098;',
			'icon-iphone' : '&#xe099;',
			'icon-compass' : '&#xe09e;',
			'icon-box' : '&#xe09f;',
			'icon-folder-stroke' : '&#xe0a0;',
			'icon-folder-fill' : '&#xe0a1;',
			'icon-at' : '&#xe0a2;',
			'icon-ampersand' : '&#xe0a3;',
			'icon-info' : '&#xe0a4;',
			'icon-question-mark' : '&#xe0a5;',
			'icon-pilcrow' : '&#xe0a6;',
			'icon-hash' : '&#xe0a7;',
			'icon-left-quote' : '&#xe0a8;',
			'icon-right-quote' : '&#xe0a9;',
			'icon-left-quote-alt' : '&#xe0aa;',
			'icon-right-quote-alt' : '&#xe0ab;',
			'icon-article' : '&#xe0ac;',
			'icon-read-more' : '&#xe0ad;',
			'icon-list' : '&#xe0ae;',
			'icon-list-nested' : '&#xe0af;',
			'icon-book' : '&#xe0b0;',
			'icon-book-alt' : '&#xe0b1;',
			'icon-book-alt2' : '&#xe0b2;',
			'icon-pen' : '&#xe0b3;',
			'icon-pen-alt-stroke' : '&#xe0b4;',
			'icon-pen-alt-fill' : '&#xe0b5;',
			'icon-pen-alt2' : '&#xe0b6;',
			'icon-brush' : '&#xe0b7;',
			'icon-brush-alt' : '&#xe0b8;',
			'icon-eyedropper' : '&#xe0b9;',
			'icon-layers-alt' : '&#xe0ba;',
			'icon-layers' : '&#xe0bb;',
			'icon-image' : '&#xe0bc;',
			'icon-camera' : '&#xe0bd;',
			'icon-aperture' : '&#xe0be;',
			'icon-aperture-alt' : '&#xe0bf;',
			'icon-chart' : '&#xe0c0;',
			'icon-chart-alt' : '&#xe0c1;',
			'icon-bars' : '&#xe0c2;',
			'icon-bars-alt' : '&#xe0c3;',
			'icon-eye' : '&#xe0c4;',
			'icon-user' : '&#xe0c5;',
			'icon-home' : '&#xe0c6;',
			'icon-clock' : '&#xe0c7;',
			'icon-lock-stroke' : '&#xe0c8;',
			'icon-lock-fill' : '&#xe0c9;',
			'icon-unlock-stroke' : '&#xe0ca;',
			'icon-unlock-fill' : '&#xe0cb;',
			'icon-tag-stroke' : '&#xe0cc;',
			'icon-tag-fill' : '&#xe0cd;',
			'icon-sun-stroke' : '&#xe0ce;',
			'icon-sun-fill' : '&#xe0d9;',
			'icon-moon-stroke' : '&#xe0da;',
			'icon-moon-fill' : '&#xe0db;',
			'icon-cloud' : '&#xe0dc;',
			'icon-rain' : '&#xe0dd;',
			'icon-umbrella' : '&#xe0de;',
			'icon-star' : '&#xe0df;',
			'icon-map-pin-stroke' : '&#xe0cf;',
			'icon-map-pin-fill' : '&#xe0d0;',
			'icon-map-pin-alt' : '&#xe0d1;',
			'icon-target' : '&#xe0d2;',
			'icon-download' : '&#xe0d3;',
			'icon-upload' : '&#xe0d4;',
			'icon-cloud-download' : '&#xe0d5;',
			'icon-cloud-upload' : '&#xe0d6;',
			'icon-fork' : '&#xe0d7;',
			'icon-paperclip' : '&#xe0d8;',
			'icon-chat' : '&#xe034;',
			'icon-chat-alt-stroke' : '&#xe035;',
			'icon-chat-alt-fill' : '&#xe036;',
			'icon-comment-alt1-stroke' : '&#xe037;',
			'icon-comment-alt1-fill' : '&#xe038;',
			'icon-comment-stroke' : '&#xe039;',
			'icon-comment-fill' : '&#xe03a;',
			'icon-comment-alt2-stroke' : '&#xe03b;',
			'icon-comment-alt2-fill' : '&#xe03c;',
			'icon-checkmark' : '&#xe03d;',
			'icon-check-alt' : '&#xe03e;',
			'icon-x' : '&#xe03f;',
			'icon-x-altx-alt' : '&#xe040;',
			'icon-denied' : '&#xe041;',
			'icon-cursor' : '&#xe042;',
			'icon-rss' : '&#xe043;',
			'icon-rss-alt' : '&#xe044;',
			'icon-wrench' : '&#xe045;',
			'icon-dial' : '&#xe046;',
			'icon-cog' : '&#xe047;',
			'icon-calendar' : '&#xe048;',
			'icon-calendar-alt-stroke' : '&#xe049;',
			'icon-calendar-alt-fill' : '&#xe04a;',
			'icon-share' : '&#xe04b;',
			'icon-mail' : '&#xe04c;',
			'icon-heart-stroke' : '&#xe04d;',
			'icon-heart-fill' : '&#xe04e;',
			'icon-movie' : '&#xe04f;',
			'icon-document-alt-stroke' : '&#xe050;',
			'icon-document-alt-fill' : '&#xe051;',
			'icon-document-stroke' : '&#xe052;',
			'icon-document-fill' : '&#xe053;',
			'icon-plus' : '&#xe054;',
			'icon-plus-alt' : '&#xe055;',
			'icon-minus' : '&#xe056;',
			'icon-minus-alt' : '&#xe057;',
			'icon-pin' : '&#xe058;',
			'icon-link' : '&#xe059;',
			'icon-bolt' : '&#xe05a;',
			'icon-move' : '&#xe05b;',
			'icon-move-alt1' : '&#xe05c;',
			'icon-move-alt2' : '&#xe05d;',
			'icon-equalizer' : '&#xe05e;',
			'icon-award-fill' : '&#xe05f;',
			'icon-award-stroke' : '&#xe060;',
			'icon-magnifying-glass' : '&#xe061;',
			'icon-trash-stroke' : '&#xe062;',
			'icon-trash-fill' : '&#xe063;',
			'icon-beaker-alt' : '&#xe064;',
			'icon-beaker' : '&#xe065;',
			'icon-key-stroke' : '&#xe066;',
			'icon-key-fill' : '&#xe067;',
			'icon-new-window' : '&#xe068;',
			'icon-lightbulb' : '&#xe069;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};